{
 "title": "Flask Metrics Dashboard",
 "tags": [
  "flask",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Window state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "is_window_open", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lower Temperature Threshold ℃",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature_threshold_min", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Temperature ℃",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Higher Temperature Threshold ℃",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature_threshold_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature Level Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature", "legendFormat": "{{__name__}}" },
    { "expr": "temperature_threshold_min", "legendFormat": "{{__name__}}" },
    { "expr": "temperature_threshold_max", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Current Air Quality 2.5PM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "air_quality_real", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Good Air Quality 2.5PM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_map{quality=\"good\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Moderate Air Quality 2.5PM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_map{quality=\"moderate\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Poor Air Quality 2.5PM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_quality_map{quality=\"poor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air Quality Level Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "2.5PM" } },
   "targets": [
    { "expr": "air_quality_real", "legendFormat": "{{__name__}}" },
    {
     "expr": "air_quality_map{quality=\"good\"}",
     "legendFormat": "{{quality}}"
    },
    {
     "expr": "air_quality_map{quality=\"moderate\"}",
     "legendFormat": "{{quality}}"
    },
    {
     "expr": "air_quality_map{quality=\"poor\"}",
     "legendFormat": "{{quality}}"
    }
   ]
  }
 ]
}